# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5829ca9238212aa248af13e9a75c5aef9f64893f287b52d4cf3bc315c8e09c6aa1f310d61d7b8ca1ad26ac0e0a4b39b49d7285e759711eaf7a9a525c8dd097e5

test:
  secret_key_base: 45994e674d4845fe862e2b99cab013a36cd886bc9b9c5a77e5563b191a861523b2a1c9bd4fef35b41b4a35db17650e5112e1e3bad0a1689f539dcfc3f5cde8eb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
